#!/usr/bin/env python3
#
# This file is part of the Robotic Observatory Control Kit (rockit)
#
# rockit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# rockit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with rockit.  If not, see <http://www.gnu.org/licenses/>.

"""Exposes the current sun and moon positions for the environment daemon"""

import argparse
import json
from astropy.coordinates import get_sun, get_moon, EarthLocation, AltAz
from astropy.time import Time
from astropy import units as u
import numpy as np
import Pyro4
from rockit.common import daemons, validation


CONFIG_SCHEMA = {
    'type': 'object',
    'additionalProperties': False,
    'required': ['daemon', 'latitude', 'longitude', 'altitude'],
    'properties': {
        'daemon': {
            'type': 'string',
            'daemon_name': True
        },
        'latitude': {
            'type': 'number',
            'minimum': -90,
            'maximum': 90
        },
        'longitude': {
            'type': 'number',
            'minimum': -180,
            'maximum': 180
        },
        'altitude': {
            'type': 'number',
            'minimum': 0
        }
    }
}


class Config:
    """Daemon configuration parsed from a json file"""
    def __init__(self, config_filename):
        # Will throw on file not found or invalid json
        with open(config_filename, 'r', encoding='utf-8') as config_file:
            config_json = json.load(config_file)

        # Will throw on schema violations
        validation.validate_config(config_json, CONFIG_SCHEMA, {
            'daemon_name': validation.daemon_name_validator
        })

        self.daemon = getattr(daemons, config_json['daemon'])
        self.latitude = float(config_json['latitude'])
        self.longitude = float(config_json['longitude'])
        self.altitude = float(config_json['altitude'])


def moon_illumination(sun_coord, moon_coord):
    """Calculate the moon illumination as a fraction between 0 and 1"""
    elongation = sun_coord.separation(moon_coord)
    phase = np.arctan2(sun_coord.distance * np.sin(elongation),
                       moon_coord.distance - sun_coord.distance * np.cos(elongation))
    return ((1 + np.cos(phase)) / 2.0).value


class EphemerisDaemon:
    """Wraps a web request to the TNG weather feed"""
    def __init__(self, config):
        # pylint: disable=no-member
        self._location = EarthLocation(lat=config.latitude*u.deg,
                                       lon=config.longitude*u.deg,
                                       height=config.altitude*u.m)
        # pylint: enable=no-member

    @Pyro4.expose
    def last_measurement(self):
        """Query the latest valid measurement.
        May return None if no data is available"""

        now = Time.now()
        frame = AltAz(obstime=now, location=self._location)
        sun = get_sun(now).transform_to(frame)
        moon = get_moon(now).transform_to(frame)

        return {
            'date': now.strftime('%Y-%m-%dT%H:%M:%SZ'),
            'sun_alt': sun.alt.value,
            'moon_alt': moon.alt.value,
            'moon_percent_illumination': round(100 * moon_illumination(sun, moon), 1)
        }


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Environment Server')
    parser.add_argument('config', help='Path to configuration json file')
    args = parser.parse_args()
    c = Config(args.config)
    c.daemon.launch(EphemerisDaemon(c))
